/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

typedef volatile unsigned int vuint32_t ;

#include <stdint.h>

//Register base addresses
#define RCC_BASE    0x40021000
#define PortA_BASE  0x40010800
#define PortB_BASE  0x40010C00

//RCC Registers
#define RCC_APB2ENR *(vuint32_t*)(RCC_BASE + 0x18)

//GPIOA Registers
#define GPIOA_CRL    *(vuint32_t*)(PortA_BASE)
#define GPIOA_CRH    *(vuint32_t*)(PortA_BASE + 0x04)
#define GPIOA_ODR    *(vuint32_t*)(PortA_BASE + 0x0c)
#define GPIOA_IDR    *(vuint32_t*)(PortA_BASE + 0x08)

//GPIOB Registers
#define GPIOB_CRL    *(vuint32_t*)(PortB_BASE)
#define GPIOB_CRH    *(vuint32_t*)(PortB_BASE + 0x04)
#define GPIOB_ODR    *(vuint32_t*)(PortB_BASE + 0x0c)
#define GPIOB_IDR    *(vuint32_t*)(PortB_BASE + 0x08)

void clock_init(){
	//Enable GPIOA Clock
	RCC_APB2ENR |= 1<<2;

	//Enable GPIOB Clock
	RCC_APB2ENR |= 1<<3;
}

void GPIO_INIT(){
	GPIOA_CRL = 0;
	GPIOB_CRL = 0;
	GPIOA_CRH = 0;
	GPIOB_CRH = 0;

	//PA[1] input HI-Z
	GPIOA_CRL |= 1<<6;

	//PB[1] output push-pull mode
	GPIOB_CRL |= 1<<4;

	//PA[13] input HI-Z
	GPIOA_CRH  |= 1<<22;

	//PB[13] output push pull mode
	GPIOB_CRH |= 1<<20;
}

int main(void)
{
	int i;
	//Initialization
	clock_init();
	GPIO_INIT();

	while(1){
		//PA[1] is connected to PUR
		if(((GPIOA_IDR & 1<<1) >> 1) == 0){ //means that the button is pressed
			GPIOB_ODR ^= 1<<1;
			while(((GPIOA_IDR & 1<<1) >> 1) == 0); //single press
		}
		//PA[13] is connected to PDR
		if(((GPIOA_IDR & 1<<13) >> 13) == 1){ //means that the button is pressed
			GPIOB_ODR ^= 1<<13;
		}
		//delay
		for(i = 0; i<550; i++);
	}
}
