/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


typedef volatile unsigned int vuint32_t ;

#include <stdint.h>

//register addresses
#define RCC_BASE    0x40021000
#define PortA_BASE  0x40010800

#define RCC_APB2ENR *(vuint32_t*)(RCC_BASE + 0x18)
#define RCC_CFGR 	*(vuint32_t*)(RCC_BASE + 0x04)
#define RCC_CR 		*(vuint32_t*)(RCC_BASE)
#define GPIOA_CRH   *(vuint32_t*)(PortA_BASE + 0x04)
#define GPIOA_ODR   *(vuint32_t*)(PortA_BASE + 0x0c)

typedef union {
	vuint32_t all_fields;
	struct{
		vuint32_t reserved:13;
		vuint32_t P_13:1;
	}Pin;
}R_ODR_t;

volatile R_ODR_t* R_ODR = (volatile R_ODR_t*)(PortA_BASE + 0x0c);

int main(void)
{
	RCC_CFGR |= 0b10; // Select PLL as System Clock
	RCC_CFGR |= 0b0110<<18; //PLL input x 8
	RCC_CFGR |= 0b101<<11; //APB2 prescaler /4
	RCC_CFGR |= 0b100<<8; //APB1 prescaler /2
	RCC_CR |= 1<<24; //PLL ON
	RCC_APB2ENR |= 1<<2; //Enable PORTA CLK
	GPIOA_CRH    &= 0xFF0FFFFF;
	GPIOA_CRH    |= 0x00200000;
	while(1){
		R_ODR->Pin.P_13 = 1;
		for(int i = 0; i<5000; i++);
		R_ODR->Pin.P_13 = 0;
		for(int i = 0; i<5000; i++);
	}
}
