/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "LCD.h"
#include "Key_Pad.h"
#include "Seven_SEG.h"

void clock_init(){

	GPIOx_CLK_EN('A');
	GPIOx_CLK_EN('B');
}

void HAL_init(){
	LCD_Init();
	SevenSeg_init();
	KEYPAD_INIT();
}

void start(){
	char lcd[10]= {'0','1','2','3','4','5','6','7','8','9'};
	char seg[10] = {ZERO,ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,EIGHT,NINE};

	LCD_Goto_XY(1,4);
	LCD_Send_A_String("Hey There!");
	LCD_Clear_Screen();

	for(int i = 0; i<10; i++){
		LCD_Goto_XY(1,8);
		LCD_Send_A_Character(lcd[i]);
		MCAL_GPIOx_WritePort(GPIOB, seg[i] << 9);
		wait_ms(100);
		LCD_Clear_Screen();
	}
	//turn off Seven SEG
	MCAL_GPIOx_WritePort(GPIOB, 0x7F << 9);
	LCD_Send_A_String("Key Pad is Ready!");
	LCD_Clear_Screen();
}

int main(void)
{
	clock_init();
	HAL_init();
	start();

	while(1){
		char pressedkey = KEYPAD_GET_KEY();
		switch(pressedkey){
		case 'A':
			break;
		case '?':
			LCD_Clear_Screen();
			break;
		default:
			LCD_Send_A_Character(pressedkey);
			break;
		}
	}
}
