/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "Platform_Types.h"
#include "GPIO.h"
#include "LCD.h"
#include "EXTI.h"

void clock_init(){

	GPIOx_CLK_EN('A');
	GPIOx_CLK_EN('B');
	AFIO_CLK_EN();
}

void IRQ9_CallBack(){
	LCD_Send_A_String("IRQ EXTI9 is happened _|-");
	LCD_Clear_Screen();
}

int main(void)
{
	clock_init();
	LCD_Init();

	EXTI_PinConfig_t pincfg;
	pincfg.EXTI_PIN = EXTI9PB9;
	pincfg.Trigger_Case = EXTI_Trigger_RISING;
	pincfg.IRQ_EN = EXTI_IRQ_Enable;
	pincfg.P_IRQ_CallBack = IRQ9_CallBack;

	MCAL_EXTI_GPIO_Init(&pincfg);

    /* Loop forever */
	for(;;);
}
