/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "Platform_Types.h"
#include "GPIO.h"
#include "EXTI.h"

uint8_t Flag;

void IRQ9_CallBack()
{
	Flag = 1;
}

int main(void)
{
	GPIOx_CLK_EN('B');

	EXTI_PinConfig_t pincfg;
	pincfg.EXTI_PIN = EXTI9PB9;
	pincfg.Trigger_Case = EXTI_Trigger_RISING;
	pincfg.IRQ_EN = EXTI_IRQ_Enable;
	pincfg.P_IRQ_CallBack = IRQ9_CallBack;

	MCAL_EXTI_GPIO_Init(&pincfg);

    /* Loop forever */
	while(1)
	{
		if(Flag) Flag = 0;
	}
}
