/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "EEPROM.h"

int main(void)
{

	GPIOx_CLK_EN('B');

	uint8_t ch1[7] = {1,2,3,4,5,6,7};
	uint8_t ch2[7] = {0};

	HAL_EEPROM_Init(I2C1);
	HAL_EEPROM_Receive(I2C1, ch1, 7, 0xaf);
	HAL_EEPROM_Send(I2C1, ch2, 7, 0xaf);

	ch1[0] = 0xa;
	ch1[1] = 0xb;
	ch1[2] = 0xc;
	ch1[3] = 0xd;

	HAL_EEPROM_Receive(I2C1, ch1, 4, 0xfff);
	HAL_EEPROM_Send(I2C1, ch2, 4, 0xfff);

	while(1);

}
