/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "Platform_Types.h"
#include "GPIO.h"
#include "EXTI.h"

enum CPUAccessLevel{
	Privileged,
	Unprivileged
};

uint8_t Flag;

void SWITCH_CPU_AccessLevel(enum CPUAccessLevel Level){

	switch(Level){

	case Privileged:
		__asm("mrs r3,CONTROL \n\t"
				"lsr r3,r3,#0x1 \n\t"
				"lsl r3,r3,#0x1 \n\t"
				"msr CONTROL,r3");
		break;

	case Unprivileged:
		__asm("mrs r3,CONTROL \n\t"
				"orr r3,r3,#0x1 \n\t"
				"msr CONTROL,r3");
		break;
	}

}

void IRQ9_CallBack()
{
	Flag = 1;
	SWITCH_CPU_AccessLevel(Privileged);
}

int main(void)
{
	GPIOx_CLK_EN('B');

	EXTI_PinConfig_t pincfg;
	pincfg.EXTI_PIN = EXTI9PB9;
	pincfg.Trigger_Case = EXTI_Trigger_RISING;
	pincfg.IRQ_EN = EXTI_IRQ_Enable;
	pincfg.P_IRQ_CallBack = IRQ9_CallBack;

	MCAL_EXTI_GPIO_Init(&pincfg);

	SWITCH_CPU_AccessLevel(Unprivileged);

	/* Loop forever */
	while(1)
	{
		if(Flag) Flag = 0;
	}
}
