/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/* ==============INCLUDES==============*/
#include <stdio.h>
#include "Servo_Motor.h"
#include "LCD.h"
#include "Key_Pad.h"
#include "LED.h"
#include "USART.h"
/*====================================*/

/*==============Generic Variables=====*/
uint16_t buffer;
char ID[3],free_slots = 3;
/*====================================*/

void free_slots_available(){

	char str[13]={0};

	LCD_Goto_XY(1, 5, ENTRY_LCD);
	LCD_Send_A_String("Welcome!",ENTRY_LCD);
	LCD_Goto_XY(3, 0, ENTRY_LCD);
	sprintf(str,"%d Free Slots",free_slots);
	LCD_Send_A_String(str,ENTRY_LCD);

}

void ENTRY_Gate(){

	MCAL_USART_ReceiveData(USART1, &buffer, disable);

	// Check if the entered id matches or not
	char isFound = 0;

	if(free_slots){
		for(int i = 0; i<3; i++){

			if(ID[i] == buffer){
				/*if entered id is found*/
				isFound = 1;
				free_slots--;

				LCD_Clear_Screen(ENTRY_LCD);
				LCD_Send_A_String("The Gate is open", ENTRY_LCD);
				Green_LED_ON();

				/* Open the Entry gate */
				Servo1_Entry_Gate(UP);
				dms(800);
				//Checks if the car has passed first to close the gate
				while(MCAL_GPIOx_ReadPin(GPIOA, GPIO_PIN_7));
				/* Close the Entry gate */
				Servo1_Entry_Gate(Down);

				LCD_Clear_Screen(ENTRY_LCD);
				free_slots_available();
			}
		}
	}else{
		LCD_Clear_Screen(ENTRY_LCD);
		LCD_Send_A_String("Parking is full", ENTRY_LCD);
		dms(80);
		LCD_Clear_Screen(ENTRY_LCD);
		free_slots_available();
	}
	/*if entered id is NOT found*/
	if(!isFound && free_slots !=0){

		LCD_Clear_Screen(ENTRY_LCD);
		LCD_Send_A_String("Wrong ID", ENTRY_LCD);
		RED_LED_ON();
		LCD_Clear_Screen(ENTRY_LCD);

		free_slots_available();

	}
}

void EXIT_Gate(){

	MCAL_USART_ReceiveData(USART2, &buffer, disable);

	// Check if the entered id matches or not
	char isFound = 0;

	if(free_slots <3){
		for(int i =0; i<3; i++){
			if(ID[i] == buffer){
				/*if entered id is found*/
				isFound = 1;
			}
		}

		/* Open the Exit gate if id exists*/
		if(isFound){
			Servo2_Exit_Gate(UP);
			dms(800);
			//Checks if the car has passed first to close the gate
			while(MCAL_GPIOx_ReadPin(GPIOA, GPIO_PIN_1));
			/* Close the Exit gate */
			Servo2_Exit_Gate(Down);

			free_slots++;
			free_slots_available();
		}
	}
}

int main(void)
{
	char key_is_pressed,str[25]={0};

	//Enable Clocks
	GPIOx_CLK_EN('A');
	GPIOx_CLK_EN('B');

	//Initialization
	LCD_Init();
	KEYPAD_INIT();
	LED_init();
	Timer2_init();
	Servo1_Entry_Gate_Init();
	Servo2_Exit_Gate_Init();

	USART_Config_t usart_cfg;

	usart_cfg.BaudRate = USART_BaudRate_115200;
	usart_cfg.HwFlowCtl = USART_HwFlowCtl_NONE;
	usart_cfg.IRQ_Enable = USART_IRQ_Enable_RXNE;
	usart_cfg.Parity = USART_Parity_NONE;
	usart_cfg.Payload_Length = USART_Payload_Length_8B;
	usart_cfg.StopBits = USART_StopBits_1;
	usart_cfg.USART_Mode = USART_Mode_Rx;
	usart_cfg.P_IRQ_CallBack = ENTRY_Gate;

	MCAL_USART_Init(USART1, &usart_cfg);
	MCAL_UASRT_GPIO_Set_Pins(USART1);

	usart_cfg.P_IRQ_CallBack = EXIT_Gate;

	MCAL_USART_Init(USART2, &usart_cfg);
	MCAL_UASRT_GPIO_Set_Pins(USART2);

	//ADMIN DashBoard ECU3
	LCD_Send_A_String("Enter users' IDs",ADMIN_LCD);
	/* Store IDs of the users */
	for(int i = 0; i<3; i++){

		LCD_Goto_XY(i+2, 4,ADMIN_LCD);
		sprintf(str,"User%d ID:",i+1);
		LCD_Send_A_String(str,ADMIN_LCD);

		while(1){

			key_is_pressed = 0;
			ID[i] = KEYPAD_GET_KEY();

			switch(ID[i]){

			case '\0':
				break;

			default:
				LCD_Send_A_Character(ID[i],ADMIN_LCD);
				key_is_pressed = 1;
				break;
			}
			if(key_is_pressed)  break;
		}
	}

	LCD_Clear_Screen(ADMIN_LCD);

	/* Display Stored IDs on ADMIN LCD*/
	sprintf(str,"Stored IDs are: %c, %c, %c",ID[0],ID[1],ID[2]);
	LCD_Send_A_String(str,ADMIN_LCD);

	/* Display Free Slots in ENTRY LCD */
	free_slots_available();

	while(1);

}
